# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 566375f3408649bd5433f0b14de01c9574b977cde4ff62448f309ea0894a416abb5192718f23de20520a6872d6cd2429cdd54625967fec4fa0092dde0eca3e7a

test:
  secret_key_base: 9517eb731c31b5cb02b7ad778785e28233012055717316789bd4bc3aa4329827c45d18ae2982a425864b9de87de03fc1c1af2b000af1d4f4bcebeb46ea6c1cb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
